export default [
    {
        id: "bow",
        name: "Bow",
        type: "state",
        states: ["None", "Bow", "Bow & Arrow", "Silver Arrow Bow", "Bow & Silver Arrows"],
        offset: 0, 
    },
    {
        id: "boomerang",
        name: "Boomerang",
        type: "state",
        states: ["None", "Blue", "Red"],
        offset: 1, 
    },
    {
        id: "hookshot",
        name: "Hookshot",
        type: "boolean",
        offset: 2, 
    },
    {
        id: "bombs",
        name: "Bombs",
        type: "count",
        offset: 3, 
    },
    {
        id: "magic-powder",
        name: "Magic Powder",
        type: "state",
        states: ["None", "Mushroom", "Magic Powder"],
        offset: 4, 
    },
    {
        id: "fire-rod",
        name: "Fire Rod",
        type: "boolean",
        offset: 5, 
    },
    {
        id: "ice-rod",
        name: "Ice Rod",
        type: "boolean",
        offset: 6, 
    },
    {
        id: "bombos-medallion",
        name: "Bombos Medallion",
        type: "boolean",
        offset: 7, 
    },
    {
        id: "ether-medallion",
        name: "Ether Medallion",
        type: "boolean",
        offset: 8, 
    },
    {
        id: "quake-medallion",
        name: "Quake Medallion",
        type: "boolean",
        offset: 9 
    },
    {
        id: "lamp",
        name: "Lamp",
        type: "boolean",
        offset: 10, 
    },
    {
        id: "magic-hammer",
        name: "Magic Hammer",
        type: "boolean",
        offset: 11, 
    },
    {
        id: "flute",
        name: "Flute",
        type: "state",
        states: ["None", "Shovel", "Flute", "Flute & Bird"],
        offset: 12, 
    },
    {
        id: "bug-net",
        name: "Bug Catching Net",
        type: "boolean",
        offset: 13, 
    },
    {
        id: "book-of-mudora",
        name: "Book of Mudora",
        type: "boolean",
        offset: 14, 
    },
    {
        id: "bottles",
        name: "Bottles",
        type: "bitset",
        offset: 15, 
    },
    {
        id: "cane-somaria",
        name: "Cane of Somaria",
        type: "boolean",
        offset: 16, 
    },
    {
        id: "cane-byrna",
        name: "Cane of Byrna",
        type: "boolean",
        offset: 17, 
    },
    {
        id: "magic-cape",
        name: "Magic Cape",
        type: "boolean",
        offset: 18, 
    },
    {
        id: "magic-mirror",
        name: "Magic Mirror",
        type: "state",
        states: ["None", "Magic Scroll", "Magic Mirror"],
        offset: 19, 
    },
    {
        id: "gloves",
        name: "Gloves",
        type: "state",
        states: ["None", "Power Glove", "Titan's Mitt"],
        offset: 20, 
    },
    {
        id: "pegasus-boots",
        name: "Pegasus Boots",
        type: "boolean",
        offset: 21, 
    },
    {
        id: "zora-flippers",
        name: "Zora's Flippers",
        type: "boolean",
        offset: 22, 
    },
    {
        id: "moon-pearl",
        name: "Moon Pearl",
        type: "boolean",
        offset: 23, 
    },
    {
        id: "sword",
        name: "Sword",
        type: "state",
        states: ["None", "Fighter's Sword", "Master Sword", "Tempered Sword", "Golden Sword"],
        offset: 25, 
    },
    {
        id: "shield",
        name: "Shield",
        type: "state",
        states: ["None", "Blue Shield", "Hero's Shield", "Mirror Shield"],
        offset: 26, 
    },
    {
        id: "armor",
        name: "Armor",
        type: "state",
        states: ["None", "Blue Mail", "Red mail"],
        offset: 27, 
    },
    {
        id: "bottle-1",
        name: "Bottle 1",
        type: "state",
        states: ["None", "Mushroom", "Empty", "Red Potion", "Green Potion", "Blue Potion", "Fairy", "Bee", "Good Bee"],
        offset: 28, 
    },
    {
        id: "bottle-2",
        name: "Bottle 2",
        type: "state",
        states: ["None", "Mushroom", "Empty", "Red Potion", "Green Potion", "Blue Potion", "Fairy", "Bee", "Good Bee"],
        offset: 29, 
    },
    {
        id: "bottle-3",
        name: "Bottle 3",
        type: "state",
        states: ["None", "Mushroom", "Empty", "Red Potion", "Green Potion", "Blue Potion", "Fairy", "Bee", "Good Bee"],
        offset: 30, 
    },
    {
        id: "bottle-4",
        name: "Bottle 4",
        type: "state",
        states: ["None", "Mushroom", "Empty", "Red Potion", "Green Potion", "Blue Potion", "Fairy", "Bee", "Good Bee"],
        offset: 31, 
    },
    {
        id: "rupees",
        name: "Rupees",
        type: "rupee-count",
        offset: 34, 
    }
];